name: srujan
description: Introducing our state-of-the-art AI-powered text editing platform that leverages the latest advancements in Natural Language Processing (NLP) to provide unparalleled accuracy and efficiency in editing and proofreading written content.  Our AI text editing platform is designed to help users improve the quality and clarity of their writing, providing real-time suggestions and corrections for grammar, punctuation, spelling, style, and syntax. With its advanced machine learning algorithms, our platform analyzes the context of the text and suggests the most appropriate corrections, ensuring that the final output is grammatically correct, easy to read, and meets the highest standards of quality.  Our platform is easy to use, providing a user-friendly interface that enables users to upload their text and receive instant feedback on their writing. The platform is customizable, allowing users to adjust the level of editing and proofreading to suit their specific needs.  The AI text editing platform is ideal for a wide range of applications, including academic writing, professional documents, and personal communication. Whether you are a student, researcher, business professional, or creative writer, our platform is the perfect tool to enhance the clarity, accuracy, and effectiveness of your writing.  With our AI text editing platform, you can save time and effort, avoid embarrassing errors and mistakes, and produce high-quality written content that effectively communicates your message to your audience. Try our platform today and experience the power of AI-driven text editing for yourself!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.0
  google_sign_in: ^6.1.0
  flutter_riverpod: ^2.3.6
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  get_it: ^7.4.1
  logger: ^1.4.0
  routemaster: ^1.0.1
  flutter_quill: ^7.2.7
  socket_io_client: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"




flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - .env


